name: twenty_nine_card_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  file_picker: ^10.3.3
  csv: ^6.0.0
  charts_flutter: ^0.12.0
  flutter_blue_plus: ^1.7.0

  # Firebase packages
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_database: ^12.0.3
  firebase_auth: ^6.1.1

  # Icons
  cupertino_icons: ^1.0.8

  # Multiplayer dependencies
  flutter_bluetooth_serial: ^0.4.0
  nearby_connections: ^4.3.0

  # Unique IDs for players
  uuid: ^4.4.0

  # Social login
  google_sign_in: ^6.1.6
  flutter_facebook_auth:
    git:
      url: https://github.com/monjur4200-creator/flutter-facebook-auth.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1
  test: ^1.24.0
  flutter_lints: ^6.0.0

  # Mock generation
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
    - assets/table/

dependency_overrides:
  # Dummy plugin to silence macOS override warning from flutter_facebook_auth
  facebook_auth_desktop:
    path: .empty_plugin